### ISSUE TITLE
Can export pictures and files, but not videos or voice messages

### ISSUE THREAD

**Issue by arun-gurung** [suurjaak/Skyperious#102]
I have sent test-files in my chat, so they are newer than 30 days. I choose "export as HTML with files in a separate folder" and it successfully exports a picture and a PDF file, but no video or voice message.

In the Skyperious chat log, the picture is uploaded into the cloud as a URI, but the PDF and video and audio says just "Sent file xx.m4a" and no URI, does it mean it is not uploaded to the cloud?

**Comment by suurjaak** [comment]
Can you post screenshots of:
- what the chat history looks like in Skyperious
- what the HTML export looks like
- what files were written to the separate export folder

**Comment by arun-gurung** [comment]
![Screenshot_2021-08-05_18-50-55](https://user-images.githubusercontent.com/28502386/128389959-ac68e466-9856-4e13-86fd-cbee1fbf6bd0.png)
![Screenshot_2021-08-05_18-52-19](https://user-images.githubusercontent.com/28502386/128389989-f5725b6f-43a4-44ed-8525-153163929e49.png)
![Screenshot_2021-08-05_18-53-22](https://user-images.githubusercontent.com/28502386/128390011-f2e441fa-1864-4496-b91e-7426daae6b5f.png)

**Comment by suurjaak** [comment]
Aha. And what does the video link point to, both inside Skyperious and in the export HTML?

**Comment by arun-gurung** [comment]
Inside Skyperious, the link points to "https://api.asm.skype.com/v1/objects/0-weu-d7-e121b2f3730aca58255b6aa83b6740c4/views/original" and in the exported HTML, it says "file:///VID_20210805_184557.mp4".

**Comment by suurjaak** [comment]
Are there any errors in the log window after running the export (menu Help -> Show log window)?

**Comment by arun-gurung** [comment]
Here's the log.

2021-08-05 20:31:33.750	Exporting chat with nn.
2021-08-05 20:31:35.016	Error calling SkypeConnection(userId='live:9b1cddbc52275d79', tokenFile=u'/home/arun-g/.local/share/Skyperious/arun-g@anubis-ca.com.token', connected=True, guest=False).

			Traceback (most recent call last):
			  File "/usr/lib/python2.7/site-packages/skyperious/live.py", line 230, in request
			    try: return func(*args, **kwargs)
			  File "/usr/lib/python2.7/site-packages/skpy/conn.py", line 237, in __call__
			    raise SkypeApiException("{0} response from {1} {2}".format(resp.status_code, method, url), resp)
			SkypeApiException: ('400 response from GET https://experimental-api.asm.skype.com/v1/objects/0-weu-d18-d8a42494260f8e91c0c09e0ad758b554/views/original', <Response [400]>)

2021-08-05 20:31:35.483	Error calling SkypeConnection(userId='live:9b1cddbc52275d79', tokenFile=u'/home/arun-g/.local/share/Skyperious/arun-g@anubis-ca.com.token', connected=True, guest=False).

			Traceback (most recent call last):
			  File "/usr/lib/python2.7/site-packages/skyperious/live.py", line 230, in request
			    try: return func(*args, **kwargs)
			  File "/usr/lib/python2.7/site-packages/skpy/conn.py", line 237, in __call__
			    raise SkypeApiException("{0} response from {1} {2}".format(resp.status_code, method, url), resp)
			SkypeApiException: ('400 response from GET https://api.asm.skype.com/v1/objects/0-weu-d18-d8a42494260f8e91c0c09e0ad758b554/views/original', <Response [400]>)

2021-08-05 20:31:44.084	Error calling SkypeConnection(userId='live:9b1cddbc52275d79', tokenFile=u'/home/arun-g/.local/share/Skyperious/arun-g@anubis-ca.com.token', connected=True, guest=False).

			Traceback (most recent call last):
			  File "/usr/lib/python2.7/site-packages/skyperious/live.py", line 230, in request
			    try: return func(*args, **kwargs)
			  File "/usr/lib/python2.7/site-packages/skpy/conn.py", line 237, in __call__
			    raise SkypeApiException("{0} response from {1} {2}".format(resp.status_code, method, url), resp)
			SkypeApiException: ('400 response from GET https://experimental-api.asm.skype.com/v1/objects/0-weu-d7-e121b2f3730aca58255b6aa83b6740c4/views/original', <Response [400]>)

2021-08-05 20:31:44.186	Error calling SkypeConnection(userId='live:9b1cddbc52275d79', tokenFile=u'/home/arun-g/.local/share/Skyperious/arun-g@anubis-ca.com.token', connected=True, guest=False).

			Traceback (most recent call last):
			  File "/usr/lib/python2.7/site-packages/skyperious/live.py", line 230, in request
			    try: return func(*args, **kwargs)
			  File "/usr/lib/python2.7/site-packages/skpy/conn.py", line 237, in __call__
			    raise SkypeApiException("{0} response from {1} {2}".format(resp.status_code, method, url), resp)
			SkypeApiException: ('400 response from GET https://api.asm.skype.com/v1/objects/0-weu-d7-e121b2f3730aca58255b6aa83b6740c4/views/original', <Response [400]>)

2021-08-05 20:31:44.414	Exported 55 messages to /home/arun-g/Desktop/Skype chat with nn.html.

**Comment by arun-gurung** [comment]
[log.odt](https://github.com/suurjaak/Skyperious/files/6940939/log.odt)

**Comment by suurjaak** [comment]
Much obliged. 

I think I've found and fixed the problem. Can I give you a pip package with a fixed Skyperious version, to install and and see if it works properly?

**Comment by arun-gurung** [comment]
Yeah, sounds good. But, how do I install a pip package?

**Comment by suurjaak** [comment]
[Skyperious-4.8.1.dev1-py2-none-any.zip](https://github.com/suurjaak/Skyperious/files/6941193/Skyperious-4.8.1.dev1-py2-none-any.zip)

Unpack the archive (had to zip it for GitHub), then open a terminal in the same directory, and run:

```
pip install Skyperious-4.8.1.dev1-py2-none-any.whl
``` 

And you need to re-run import from live before exporting.

**Comment by arun-gurung** [comment]
Now it exported my video and audio message also. Splendid, thanks so much! I want to donate a little for your efforts, the app is very useful.

**Comment by suurjaak** [comment]
Excellent. I will issue an official fixed release also at some point. I will keep this issue open until then. 

You have a point about the URI links differing inside Skyperious.. Maybe I should standardize them. 

I appreciate the sentiment :) rather donate to a local charity of your choice instead.

**Comment by arun-gurung** [comment]
Still no updated release?

**Comment by suurjaak** [comment]
I was planning to work on the file/media links difference, but did not get around to it. And looking at my schedule, will not be able to, for some time. 

So, I've issued the fixed release now. 


Thank you for reminding me.
