### ISSUE TITLE
TypeError: cannot use a string pattern on a bytes-like object

### ISSUE THREAD

**Issue by 1337-537h** [suurjaak/Skyperious#107]
From log:

022-04-27 21:03:42.193	An unexpected error has occurred:

			Traceback (most recent call last):
			  File "skyperious\gui.py", line 5108, in on_filter_chat
			  File "skyperious\gui.py", line 8057, in RefreshMessages
			  File "skyperious\gui.py", line 8144, in _write_element
			  File "skyperious\gui.py", line 8165, in _append_text
			TypeError: cannot use a string pattern on a bytes-like object

windows 10 x64

**Comment by suurjaak** [comment]
Confirmed. Will issue a fixed release soon. 

Thank you for reporting this.

**Comment by suurjaak** [comment]
Fixed in the newly released v5.1.
