### ISSUE TITLE
NameError: name 'db' is not defined

### ISSUE THREAD

**Issue by jon-62** [suurjaak/Skyperious#110]
Hello,

I can't import a json file.  I receive the following message:

2022-06-07 12:55:35.751	Started application.
2022-06-07 12:55:58.141	An unexpected error has occurred:

			Traceback (most recent call last):
			  File "skyperious\gui.py", line 1807, in on_new_export
			  File "six.py", line 719, in reraise
			  File "skyperious\gui.py", line 1803, in on_new_export
			  File "skyperious\live.py", line 1009, in __init__
			NameError: name 'db' is not defined

**Comment by suurjaak** [comment]
Confirmed.

Will issue a fixed release soon.

**Comment by suurjaak** [comment]
Should be fixed in the newly released v5.2 - can you confirm?

**Comment by jon-62** [comment]
Yes, I was able to import the json file successfully.  Thank you!
