### ISSUE TITLE
Can't open certain group chats

### ISSUE THREAD

**Issue by Jeej-Explosive** [suurjaak/Skyperious#115]
So, I had been using Skyperious to sync chats without any issue for the past 6 months, with my last sync being some 2 weeks ago. However, I resetted my PC last weekend and I suddenly started getting these errors when I tried to sync my chats all over again:

> Error saving message SkypeFileMsg(id='1669251914998', type='RichText/Media_GenericFile', time=datetime.datetime(2022, 11, 24, 1, 5, 13, 569000), clientId='13454653869419961435', userId='xxx', chatId='19:83fcb19e4f8948b68585bbeae6febb29@thread.skype', content='').

			Traceback (most recent call last):
			  File "skyperious\live.py", line 807, in populate_history
			  File "skyperious\live.py", line 249, in save
			  File "skyperious\live.py", line 683, in convert
			AttributeError: 'NoneType' object has no attribute 'urlFull'
This happens during the syncing, the following happens when I try to load the group chat after it's over:

> Error loading group chat "xxx".

			Traceback (most recent call last):
			  File "skyperious\gui.py", line 5744, in load_chat
			  File "skyperious\gui.py", line 8269, in Populate
			  File "skyperious\gui.py", line 8066, in RefreshMessages
			  File "skyperious\skypedata.py", line 1837, in parse
			  File "skyperious\skypedata.py", line 2101, in parse_message_dom
			AttributeError: 'NoneType' object has no attribute 'get'
This is just an example, but it seems to be the standard. The thing is: this seems to only happen to chats that are large and recent, and it happens only after a certain limit of messages is reached (which is really low, like 500 messages). Before the sync gets there, the chat loads just fine. 
Until recently, I was able to open them just fine, and I also can load everything on my Skype Web. Is it a problem with certain messages in these chats?

**Comment by Jeej-Explosive** [comment]
Nevermind, I just read the last issue and the pre-release fixed it for me, thank you!

**Comment by suurjaak** [comment]
v5.4 has now been released as well.
