### ISSUE TITLE
crash when opening database

### ISSUE THREAD

**Issue by glensc** [suurjaak/Skyperious#23]
I launched GUI (this time it started up), opened `main.db` and in few seconds it crashed. below is gdb backtrace. If you need more symbols from gtk libraries, i can probably install debug package of it. i can probably share that vagrant image as well where it's reproducible.

```
vagrant@pld share/skyperious$ gdb --args python src/main.pyc
GNU gdb (GDB) 7.6.2-1 (PLD Linux)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i686-pld-linux".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/bin/python2.7...(no debugging symbols found)...done.
(gdb) r
Starting program: /usr/bin/python src/main.pyc
warning: Could not load shared library symbols for linux-gate.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/libthread_db.so.1".
[New Thread 0xab7f8b40 (LWP 3141)]
[New Thread 0xaadffb40 (LWP 3142)]
[New Thread 0xaa3ffb40 (LWP 3143)]
[New Thread 0xa9bfeb40 (LWP 3144)]
[New Thread 0xa93fdb40 (LWP 3145)]
[New Thread 0xa8bfcb40 (LWP 3146)]
[Thread 0xa93fdb40 (LWP 3145) exited]
[Thread 0xaa3ffb40 (LWP 3143) exited]
[New Thread 0xaa3ffb40 (LWP 3147)]
[New Thread 0xa93fdb40 (LWP 3148)]
[Thread 0xaa3ffb40 (LWP 3147) exited]
[Thread 0xa9bfeb40 (LWP 3144) exited]
[New Thread 0xa9bfeb40 (LWP 3149)]

(main.pyc:3137): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed

(main.pyc:3137): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed

Program received signal SIGSEGV, Segmentation fault.
0xb692e319 in ?? () from /usr/lib/libgtk-x11-2.0.so.0
(gdb) bt
#0  0xb692e319 in ?? () from /usr/lib/libgtk-x11-2.0.so.0
#1  0xb69475d1 in ?? () from /usr/lib/libgtk-x11-2.0.so.0
#2  0xb692b673 in ?? () from /usr/lib/libgtk-x11-2.0.so.0
#3  0xb689ebba in ?? () from /usr/lib/libgtk-x11-2.0.so.0
#4  0xb61bc0c7 in g_closure_invoke () from /usr/lib/libgobject-2.0.so.0
#5  0xb61cd0d3 in ?? () from /usr/lib/libgobject-2.0.so.0
#6  0xb61d45b9 in g_signal_emit_valist () from /usr/lib/libgobject-2.0.so.0
#7  0xb61d4ce5 in g_signal_emit_by_name () from /usr/lib/libgobject-2.0.so.0
#8  0xb694e1c2 in ?? () from /usr/lib/libgtk-x11-2.0.so.0
#9  0xb61c300b in g_object_set_valist () from /usr/lib/libgobject-2.0.so.0
#10 0xb69350f0 in gtk_text_buffer_create_tag () from /usr/lib/libgtk-x11-2.0.so.0
#11 0xb70f5af3 in ?? () from /usr/lib/libwx_gtk2u_core-3.0.so.0
#12 0xb70f5f61 in wxTextCtrl::DoSetValue(wxString const&, int) () from /usr/lib/libwx_gtk2u_core-3.0.so.0
#13 0xb70f6ac0 in ?? () from /usr/lib/libwx_gtk2u_core-3.0.so.0
#14 0xb75509ad in ?? () from /usr/lib/python2.7/site-packages/wx/_core_.so
#15 0xb7ea7846 in PyCFunction_Call () from /usr/lib/libpython2.7.so.1.0
#16 0xb7eff342 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#17 0xb7effd26 in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#18 0xb7e94152 in ?? () from /usr/lib/libpython2.7.so.1.0
#19 0xb7e70bb3 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#20 0xb7e70c7e in ?? () from /usr/lib/libpython2.7.so.1.0
#21 0xb7e70cf4 in PyObject_CallFunction () from /usr/lib/libpython2.7.so.1.0
#22 0xb7e853d2 in ?? () from /usr/lib/libpython2.7.so.1.0
#23 0xb7ea9f8b in _PyObject_GenericSetAttrWithDict () from /usr/lib/libpython2.7.so.1.0
#24 0xb7eaa0ff in PyObject_GenericSetAttr () from /usr/lib/libpython2.7.so.1.0
#25 0xb7ea99a0 in PyObject_SetAttr () from /usr/lib/libpython2.7.so.1.0
#26 0xb7efbce1 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#27 0xb7effd26 in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#28 0xb7efed96 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#29 0xb7efef3f in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#30 0xb7effd26 in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#31 0xb7e94152 in ?? () from /usr/lib/libpython2.7.so.1.0
#32 0xb7e70bb3 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#33 0xb7e7ece5 in ?? () from /usr/lib/libpython2.7.so.1.0
#34 0xb7e70bb3 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#35 0xb7ec20dd in ?? () from /usr/lib/libpython2.7.so.1.0
#36 0xb7ec0ac8 in ?? () from /usr/lib/libpython2.7.so.1.0
#37 0xb7e70bb3 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#38 0xb7efc49a in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#39 0xb7effd26 in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#40 0xb7efed96 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#41 0xb7effd26 in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#42 0xb7e94152 in ?? () from /usr/lib/libpython2.7.so.1.0
#43 0xb7e70bb3 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#44 0xb7e7ece5 in ?? () from /usr/lib/libpython2.7.so.1.0
#45 0xb7e70bb3 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#46 0xb7ef9112 in PyEval_CallObjectWithKeywords () from /usr/lib/libpython2.7.so.1.0
#47 0xb74cba96 in wxPyCallback::EventThunker(wxEvent&) () from /usr/lib/python2.7/site-packages/wx/_core_.so
#48 0xb6d09a40 in wxAppConsoleBase::HandleEvent(wxEvtHandler*, void (wxEvtHandler::*)(wxEvent&), wxEvent&) const () from /usr/lib/libwx_baseu-3.0.so.0
#49 0xb6d09df1 in wxAppConsoleBase::CallEventHandler(wxEvtHandler*, wxEventFunctor&, wxEvent&) const () from /usr/lib/libwx_baseu-3.0.so.0
#50 0xb6e47f20 in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) () from /usr/lib/libwx_baseu-3.0.so.0
#51 0xb6e4822e in wxEvtHandler::SearchDynamicEventTable(wxEvent&) () from /usr/lib/libwx_baseu-3.0.so.0
#52 0xb6e4827c in wxEvtHandler::TryHereOnly(wxEvent&) () from /usr/lib/libwx_baseu-3.0.so.0
#53 0xb6e48319 in wxEvtHandler::ProcessEventLocally(wxEvent&) () from /usr/lib/libwx_baseu-3.0.so.0
#54 0xb6e48371 in wxEvtHandler::ProcessEvent(wxEvent&) () from /usr/lib/libwx_baseu-3.0.so.0
#55 0xb7525892 in ?? () from /usr/lib/python2.7/site-packages/wx/_core_.so
#56 0xb7ea7846 in PyCFunction_Call () from /usr/lib/libpython2.7.so.1.0
#57 0xb7eff342 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#58 0xb7effd26 in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#59 0xb7efed96 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#60 0xb7effd26 in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#61 0xb7efed96 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#62 0xb7effd26 in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#63 0xb7e94152 in ?? () from /usr/lib/libpython2.7.so.1.0
#64 0xb7e70bb3 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#65 0xb7e7ece5 in ?? () from /usr/lib/libpython2.7.so.1.0
#66 0xb7e70bb3 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#67 0xb7ef9112 in PyEval_CallObjectWithKeywords () from /usr/lib/libpython2.7.so.1.0
#68 0xb74cba96 in wxPyCallback::EventThunker(wxEvent&) () from /usr/lib/python2.7/site-packages/wx/_core_.so
#69 0xb6d09a40 in wxAppConsoleBase::HandleEvent(wxEvtHandler*, void (wxEvtHandler::*)(wxEvent&), wxEvent&) const () from /usr/lib/libwx_baseu-3.0.so.0
#70 0xb6d09df1 in wxAppConsoleBase::CallEventHandler(wxEvtHandler*, wxEventFunctor&, wxEvent&) const () from /usr/lib/libwx_baseu-3.0.so.0
#71 0xb6e47f20 in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) () from /usr/lib/libwx_baseu-3.0.so.0
#72 0xb6e4822e in wxEvtHandler::SearchDynamicEventTable(wxEvent&) () from /usr/lib/libwx_baseu-3.0.so.0
#73 0xb6e4827c in wxEvtHandler::TryHereOnly(wxEvent&) () from /usr/lib/libwx_baseu-3.0.so.0
#74 0xb6e48319 in wxEvtHandler::ProcessEventLocally(wxEvent&) () from /usr/lib/libwx_baseu-3.0.so.0
#75 0xb6e48371 in wxEvtHandler::ProcessEvent(wxEvent&) () from /usr/lib/libwx_baseu-3.0.so.0
#76 0xb7216c16 in wxScrollHelperEvtHandler::ProcessEvent(wxEvent&) () from /usr/lib/libwx_gtk2u_core-3.0.so.0
#77 0xb6e48140 in wxEvtHandler::SafelyProcessEvent(wxEvent&) () from /usr/lib/libwx_baseu-3.0.so.0
#78 0xb71d0b7a in wxWindowBase::HandleWindowEvent(wxEvent&) const () from /usr/lib/libwx_gtk2u_core-3.0.so.0
#79 0xb70890e5 in wxWindow::GTKProcessEvent(wxEvent&) const () from /usr/lib/libwx_gtk2u_core-3.0.so.0
#80 0xb708e913 in ?? () from /usr/lib/libwx_gtk2u_core-3.0.so.0
#81 0xb689c861 in ?? () from /usr/lib/libgtk-x11-2.0.so.0
#82 0xb61bc0c7 in g_closure_invoke () from /usr/lib/libgobject-2.0.so.0
#83 0xb61cd0d3 in ?? () from /usr/lib/libgobject-2.0.so.0
#84 0xb61d42d3 in g_signal_emit_valist () from /usr/lib/libgobject-2.0.so.0
#85 0xb61d4848 in g_signal_emit () from /usr/lib/libgobject-2.0.so.0
#86 0xb69b4f52 in ?? () from /usr/lib/libgtk-x11-2.0.so.0
#87 0xb689ae74 in gtk_propagate_event () from /usr/lib/libgtk-x11-2.0.so.0
#88 0xb689b23d in gtk_main_do_event () from /usr/lib/libgtk-x11-2.0.so.0
#89 0xb67232a7 in ?? () from /usr/lib/libgdk-x11-2.0.so.0
#90 0xb6004266 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#91 0xb60045b1 in ?? () from /usr/lib/libglib-2.0.so.0
#92 0xb600486f in g_main_loop_run () from /usr/lib/libglib-2.0.so.0
#93 0xb689a17b in gtk_main () from /usr/lib/libgtk-x11-2.0.so.0
#94 0xb7074a0d in wxGUIEventLoop::DoRun() () from /usr/lib/libwx_gtk2u_core-3.0.so.0
#95 0xb6d3b226 in wxEventLoopBase::Run() () from /usr/lib/libwx_baseu-3.0.so.0
#96 0xb6d0a7e6 in wxAppConsoleBase::MainLoop() () from /usr/lib/libwx_baseu-3.0.so.0
#97 0xb74d0d97 in wxPyApp::MainLoop() () from /usr/lib/python2.7/site-packages/wx/_core_.so
#98 0xb7531064 in ?? () from /usr/lib/python2.7/site-packages/wx/_core_.so
#99 0xb7ea77ae in PyCFunction_Call () from /usr/lib/libpython2.7.so.1.0
#100 0xb7eff342 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#101 0xb7effd26 in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#102 0xb7e94152 in ?? () from /usr/lib/libpython2.7.so.1.0
#103 0xb7e70bb3 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#104 0xb7e7ece5 in ?? () from /usr/lib/libpython2.7.so.1.0
#105 0xb7e70bb3 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
#106 0xb7efc49a in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#107 0xb7efef3f in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#108 0xb7efef3f in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#109 0xb7effd26 in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#110 0xb7efed96 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#111 0xb7effd26 in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#112 0xb7effe75 in PyEval_EvalCode () from /usr/lib/libpython2.7.so.1.0
#113 0xb7f19186 in PyRun_SimpleFileExFlags () from /usr/lib/libpython2.7.so.1.0
#114 0xb7f1946b in PyRun_AnyFileExFlags () from /usr/lib/libpython2.7.so.1.0
#115 0xb7f2955f in Py_Main () from /usr/lib/libpython2.7.so.1.0
#116 0x08048557 in main ()
(gdb) 
```

**Comment by suurjaak** [comment]
A new Skyperious version, 3.3, has been released, with a number of bugfixes. Can you check whether these errors are gone?

**Comment by suurjaak** [comment]
Closing the issue, as no more feedback coming. Please reopen if the problem actually persists.

**Comment by linuxstudio** [comment]
This is happening to me: 
Skyperious version 3.4.1, 29.04.2015
Ubuntu version 15.04

* installed skyperious according to instructions https://suurjaak.github.io/Skyperious/install.html
* launched skyperious from command line
* tried to open a database
* program crashes with "Bus error (core dumped)"
and a lot of Gdk-CRITICAL errors:
    
    francesco@lattidude:~$ skyperious
    
    (skyperious:22448): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed
    
    (skyperious:22448): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed
    
     (skyperious:22448): Gdk-CRITICAL **: IA__gdk_window_thaw_updates: assertion 'impl_window->update_freeze_count > 0' failed
    
    (skyperious:22448): Gdk-CRITICAL **: IA__gdk_window_thaw_updates: assertion 'impl_window->update_freeze_count > 0' failed
    
    (skyperious:22448): Gdk-CRITICAL **: IA__gdk_window_thaw_updates: assertion 'impl_window->update_freeze_count > 0' failed
    
    (skyperious:22448): Gdk-CRITICAL **: IA__gdk_window_thaw_updates: assertion 'impl_window->update_freeze_count > 0' failed
    
    (skyperious:22448): Gdk-CRITICAL **: IA__gdk_window_thaw_updates: assertion 'impl_window->update_freeze_count > 0' failed
    
    (skyperious:22448): Gdk-CRITICAL **: IA__gdk_window_thaw_updates: assertion 'impl_window->update_freeze_count > 0' failed
    
    (skyperious:22448): Gdk-CRITICAL **: IA__gdk_window_thaw_updates: assertion 'impl_window->update_freeze_count > 0' failed
    
    (skyperious:22448): Gdk-CRITICAL **: IA__gdk_window_thaw_updates: assertion 'impl_window->update_freeze_count > 0' failed
    
    (skyperious:22448): Gdk-CRITICAL **: IA__gdk_window_thaw_updates: assertion 'impl_window->update_freeze_count > 0' failed
    Bus error (core dumped)

**Comment by suurjaak** [comment]
Confirmed, on Ubuntu 15.04 there are big problems with crashes and overall UI layout. Looking into this.

**Comment by glensc** [comment]
altho @linuxstudio hijacked this bugreport (should had reported new bug, as this is about crash in pld linux), i upgraded  to 3.5, and i still experience segfault. will try to provide better backtrace later

```
$ skyperious --version
usage: skyperious [-h] [--verbose] {export,search,merge,diff,gui} ...
skyperious: error: too few arguments
$ skyperious 
Segmentation fault (core dumped)
```
before crash, i noticed some GUI window being painted, and then boom.

**Comment by linuxstudio** [comment]
The bug was not clearly referencing PLD Linux. If @glensc had put that in the title before, I would have opened another bug. Peace and love.

**Comment by Tailszefox** [comment]
I've identified that commenting the following line prevents Skyperious from crashing with a segfault when loading a database, at least for me:

https://github.com/suurjaak/Skyperious/blob/master/skyperious/controls.py#L123

However, it also removes the loading notice, so clearly there's something else happening. But for users having this issue, it might be worth as a temporary workaround if you don't mind losing the loading screen.

**Comment by suurjaak** [comment]
Closing the issue, as Skyperious has become obsolete.
