### ISSUE TITLE
Issue Opening Database

### ISSUE THREAD

**Issue by Bitera** [suurjaak/Skyperious#35]
Hi, I recently pulled an old Skype main.db off of a computer that I stopped using in 2009. It's definitely .db and not .dbb, but I seem to be having trouble opening it with Skyperius. When I try, I get the following message: 

```
Traceback (most recent call last):
  File "C:\stuff\projektid\skyperious\dist\build\pyinstaller\out00-PYZ.pyz\skyperious", line 1353, in on_open_current_database
  File "C:\stuff\projektid\skyperious\dist\build\pyinstaller\out00-PYZ.pyz\skyperious", line 1729, in load_database_page
  File "C:\stuff\projektid\skyperious\dist\build\pyinstaller\out00-PYZ.pyz\skyperious", line 1872, in __init__
  File "C:\stuff\projektid\skyperious\dist\build\pyinstaller\out00-PYZ.pyz\skyperious", line 2637, in create_page_info
  File "C:\stuff\projektid\skyperious\dist\build\pyinstaller\out00-PYZ.pyz\skyperious", line 2732, in update_accountinfo
TypeError: unsupported operand type(s) for ** or pow(): 'float' and 'NoneType'
```

Is there something that can be done about this, or is there just something wrong with my old database?

**Comment by suurjaak** [comment]
This error can definitely be fixed in the program. Can you try [this development release](http://erki.lap.ee/skyperious/skyperious_3.3.1g_x64.exe)?

If that one gets the database open, could you tell me the results of running this query in the SQL window:

    SELECT skypeout_balance, skypeout_precision, skypeout_balance_currency FROM Accounts

**Comment by Bitera** [comment]
That seems to have done it for opening it, however it doesn't seem to be able to export the chats. At least, not all at once. I haven't had the chance to try to export them separately to narrow it down. But, this is the message I get:

```
18:07:48.076	Error exporting chats:
		
		Traceback (most recent call last):
		  File "C:\stuff\projektid\skyperious\dist\build\pyinstaller\out00-PYZ.pyz\skyperious", line 3343, in on_export_chats
		  File "C:\stuff\projektid\skyperious\dist\build\pyinstaller\out00-PYZ.pyz\export", line 121, in export_chats
		  File "C:\stuff\projektid\skyperious\dist\build\pyinstaller\out00-PYZ.pyz\export", line 200, in export_chat_template
		  File "C:\stuff\projektid\skyperious\dist\build\pyinstaller\out00-PYZ.pyz\skypedata", line 2225, in get_collected_stats
		MemoryError
```

 And, here's what the table you asked for looks like:

  | skypeout_balance | skypeout_precision | skypeout_balance_currency
------------ | ------------- | ------------- | -------------
**1** | 100 |   | FREECALL

**Comment by suurjaak** [comment]
Good that the initial problem is fixed.

About this new error, it looks like collecting wordcloud statistics starts eating too much memory.

How large is this database? Can you open Windows Task Manager and see how much memory is the skyperious.exe process taking during export?

**Comment by Bitera** [comment]
I think the database is definitely a sizable one at 267.92 MB. It's not the largest I've worked with, but that was before the update that added the word clouds, so I suppose that makes sense. It looks like it gets through a chat with 133,963 messages using around 500,000 K of memory. Then the next chat is 381,256 messages and it gets up to around 1,500,000 K before stopping and giving that error.

**Comment by suurjaak** [comment]
Those are some pretty hefty chats indeed.. I took steps to optimize memory usage in statistics collection - can you try if [development release 3.3.1j](http://erki.lap.ee/skyperious/skyperious_3.3.1j_x64.exe) works better?

**Comment by Bitera** [comment]
Awesome, that did it. Everything looks like it got exported without error. Thanks for your help!

**Comment by suurjaak** [comment]
Excellent, glad to hear that. I have some other changes in progress, so the official update will come in a while.

Out of curiosity, and if you're up to checking it - how much memory does exporting the 381,256 messages take now?
