### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by Cyandrell** [suurjaak/Skyperious#38]
Hi,
First time I ever come on GitHub, so I don't know how issues got to be mentionned.
I tried to merge 2 .db (got 4 of this to merge actually), and a "MemoryError" occured.
Is there a way to get through this ?
I even tried to merge only one (very big) chat from a .db to another, and still this "MemoryError" occured. 
Thanks !

**Comment by suurjaak** [comment]
Is there more information on this error in the log window (from menu Help -> Show log window)?

**Comment by Cyandrell** [comment]
Assuming the "main corrupt.db" is a rename I gave to the file. And I checked the file with the tool, it's not considered as corrupted. I even tried with other .db.

Thanks !


01:40:01.159	Opened C:\Users\FloGaming64\Documents\Skype db\main corrupt.db (38.68 MB).
01:40:01.165	Opened C:\Users\FloGaming64\Documents\Skype db\main.db (10.92 MB).
01:40:01.168	Merge page for C:\Users\FloGaming64\Documents\Skype db\main corrupt.db and C:\Users\FloGaming64\Documents\Skype db\main.db.
01:40:01.250	Conversations and participants: retrieving all (C:\Users\FloGaming64\Documents\Skype db\main corrupt.db).
01:40:01.380	Conversations and participants retrieved (364 chats, 328 contacts, C:\Users\FloGaming64\Documents\Skype db\main corrupt.db).
01:40:01.380	Conversations and participants: retrieving all (C:\Users\FloGaming64\Documents\Skype db\main.db).
01:40:01.456	Conversations and participants retrieved (270 chats, 90 contacts, C:\Users\FloGaming64\Documents\Skype db\main.db).
01:40:01.777	Statistics collection starting (C:\Users\FloGaming64\Documents\Skype db\main corrupt.db).
01:40:01.933	Statistics collected (C:\Users\FloGaming64\Documents\Skype db\main corrupt.db).
01:40:01.933	Statistics collection starting (C:\Users\FloGaming64\Documents\Skype db\main.db).
01:40:01.981	Statistics collected (C:\Users\FloGaming64\Documents\Skype db\main.db).
01:40:21.174	Merging any differences from C:\Users\FloGaming64\Documents\Skype db\main corrupt.db to C:\Users\FloGaming64\Documents\Skype db\main.db.
01:57:47.324	Scan and merge error.
		
		Traceback (most recent call last):
		  File "C:\stuff\projektid\skyperious\dist\build\pyinstaller\out00-PYZ.pyz\workers", line 502, in work_diff_merge_left
		  File "C:\stuff\projektid\skyperious\dist\build\pyinstaller\out00-PYZ.pyz\workers", line 694, in get_chat_diff_left
		  File "C:\stuff\projektid\skyperious\dist\build\pyinstaller\out00-PYZ.pyz\skypedata", line 1544, in parse
		  File "C:\stuff\projektid\skyperious\dist\build\pyinstaller\out00-PYZ.pyz\skypedata", line 1973, in dom_to_text
		  File "C:\stuff\projektid\skyperious\dist\build\pyinstaller\out00-PYZ.pyz\skypedata", line 1973, in dom_to_text
		  File "C:\stuff\projektid\skyperious\dist\build\pyinstaller\out00-PYZ.pyz\skypedata", line 1973, in dom_to_text
		  File "C:\stuff\projektid\skyperious\dist\build\pyinstaller\out00-PYZ.pyz\skypedata", line 1973, in dom_to_text
		  File "C:\stuff\projektid\skyperious\dist\build\pyinstaller\out00-PYZ.pyz\skypedata", line 1973, in dom_to_text
		  File "C:\stuff\projektid\skyperious\dist\build\pyinstaller\out00-PYZ.pyz\skypedata", line 1973, in dom_to_text
		  File "C:\stuff\projektid\skyperious\dist\build\pyinstaller\out00-PYZ.pyz\skypedata", line 1973, in dom_to_text
		  File "C:\stuff\projektid\skyperious\dist\build\pyinstaller\out00-PYZ.pyz\skypedata", line 1973, in dom_to_text
		  File "C:\stuff\projektid\skyperious\dist\build\pyinstaller\out00-PYZ.pyz\skypedata", line 1973, in dom_to_text
		  File "C:\stuff\projektid\skyperious\dist\build\pyinstaller\out00-PYZ.pyz\skypedata", line 1973, in dom_to_text
		  File "C:\stuff\projektid\skyperious\dist\build\pyinstaller\out00-PYZ.pyz\skypedata", line 1973, in dom_to_text
		  File "C:\stuff\projektid\skyperious\dist\build\pyinstaller\out00-PYZ.pyz\skypedata", line 1973, in dom_to_text
		  File "C:\stuff\projektid\skyperious\dist\build\pyinstaller\out00-PYZ.pyz\skypedata", line 1973, in dom_to_text
		  File "C:\stuff\projektid\skyperious\dist\build\pyinstaller\out00-PYZ.pyz\skypedata", line 1973, in dom_to_text
		  File "C:\stuff\projektid\skyperious\dist\build\pyinstaller\out00-PYZ.pyz\skypedata", line 1973, in dom_to_text
		  File "C:\stuff\projektid\skyperious\dist\build\pyinstaller\out00-PYZ.pyz\skypedata", line 1973, in dom_to_text
		  File "C:\stuff\projektid\skyperious\dist\build\pyinstaller\out00-PYZ.pyz\skypedata", line 1973, in dom_to_text
		MemoryError
		
01:59:12.120	Conversations and participants: retrieving all (C:\Users\FloGaming64\Documents\Skype db\main.db).
01:59:12.189	Conversations and participants retrieved (270 chats, 90 contacts, C:\Users\FloGaming64\Documents\Skype db\main.db).
01:59:12.298	Statistics collection starting (C:\Users\FloGaming64\Documents\Skype db\main corrupt.db).
01:59:12.455	Statistics collected (C:\Users\FloGaming64\Documents\Skype db\main corrupt.db).
01:59:12.455	Statistics collection starting (C:\Users\FloGaming64\Documents\Skype db\main.db).
01:59:12.503	Statistics collected (C:\Users\FloGaming64\Documents\Skype db\main.db).

**Comment by suurjaak** [comment]
Looks like there is a message with some very unusual structure.

Can you run this test version: http://erki.lap.ee/skyperious/skyperious_3.5a_test_x64.exe. It will write a file named parselog.txt to its current directory during merging. Try the merge again and once the error occurs, open the text file and send me its last entry (you can censor any personal information).

**Comment by Cyandrell** [comment]
Thanks, I'll test with this version and will come back.

**Comment by Cyandrell** [comment]
Here it is :

Parsing message with body:
<URIObject content-type="image/jpeg" uri="https://api.asm.skype.com/v1//objects/0-weu-d4-f55e806e518949c6b84dc71666531c12"><Text>Pour afficher cette photo partagée, rendez-vous sur la page : <a href="https://api.asm.skype.com/s/i?0-weu-d4-f55e806e518949c6b84dc71666531c12">https://api.asm.skype.com/s/i?0-weu-d4-f55e806e518949c6b84dc71666531c12</a></Text><meta type="photo" subtype=""></meta></URIObject>

**Comment by Cyandrell** [comment]
And by the way, the error occured way quickier than with the previous version of your software. I'm not entirely sure it was the same error though.

**Comment by suurjaak** [comment]
I fear that GitHub might have removed some of the message formatting. Can you put it on a pastebin, like https://bpaste.net?

Can you also paste the new error from the log window?

**Comment by Cyandrell** [comment]
Ah yea, didn't even see.

https://bpaste.net/show/97ab9b69106d

**Comment by suurjaak** [comment]
Aha, that is actually a different error indeed, brought on by yet unpublished changes in Skyperious.

I fixed this error, can you try again: 
http://erki.lap.ee/skyperious/skyperious_3.5b_test_x64.exe?

**Comment by Cyandrell** [comment]
Ok !
I'll do that and be right back.

**Comment by Cyandrell** [comment]
So here we go : 
The error : 
https://bpaste.net/show/dc62f4f5e451

The last entry in the parselog : 
https://bpaste.net/show/5fd944e418ec

**Comment by suurjaak** [comment]
Thank you, with this information I can figure out the problem.

**Comment by suurjaak** [comment]
Ok, I think I have it fixed now. Can you try doing the merge with this version:
http://erki.lap.ee/skyperious/skyperious_3.5c_x64.exe

And does the thing with first time program launch shutting down still happen?

**Comment by Cyandrell** [comment]
Hey. I was unable to try if it fixed the problem.
The program still shut down when I launch it the first time.
With the first .db it worked just well, thanks ! I'll come back after I merged it all.

**Comment by Cyandrell** [comment]
It worked just fine ! Perfect ! Thanks !

**Comment by suurjaak** [comment]
Glad to hear the merge problem is solved. An officially fixed release will come after a while.

But the program shutting down on first launch is troubling. And puzzling. This is something I've never encountered before. What operating system are you using - Windows 7, 64bit?

**Comment by Cyandrell** [comment]
It's not really shutting down, it's just a reboot. The window opens, then closes, then opens again. 
I run Windows 7, 64 bits indeed.

**Comment by suurjaak** [comment]
Well, that is.. rather strange. I'm afraid I'm at a loss about this one.

**Comment by suurjaak** [comment]
Memory fix pushed to official release.
