### ISSUE TITLE
Loading extremely large chats still crashes the program.

### ISSUE THREAD

**Issue by rikai** [suurjaak/Skyperious#41]
Step 1:
1. Open a DB with an extremely large chat (The chat i'm using for my example contains over 1 million lines, the next largest chat at just over 114,000 lines doesn't cause the issue)
2. Load the large chat in that DB
3. Choose "from the beginning"
4. Program freezes, and eventually errors with the following:
    ---------------------------
    Unhandled exception
    ---------------------------
    An unhandled exception occurred. Press "Abort" to terminate the program,

```
"Retry" to exit the program normally and "Ignore" to try to continue.
---------------------------
Abort   Retry   Ignore
---------------------------
```

As well as some tracebacks:

```
Traceback (most recent call last):
  File "C:\stuff\projektid\skyperious\dist\build\pyinstaller\out00-PYZ.pyz\wx._misc", line 1367, in Notify
  File "C:\stuff\projektid\skyperious\dist\build\pyinstaller\out00-PYZ.pyz\wx._core", line 16869, in Notify
Traceback (most recent call last):
  File "C:\stuff\projektid\skyperious\dist\build\pyinstaller\out00-PYZ.pyz\wx.lib.agw.flatnotebook", line 5204, in OnPaint
  File "C:\stuff\projektid\skyperious\dist\build\pyinstaller\out00-PYZ.pyz\wx.lib.agw.flatnotebook", line 2356, in DrawTabs
  File "C:\stuff\projektid\skyperious\dist\build\pyinstaller\out00-PYZ.pyz\wx.lib.agw.flatnotebook", line 2782, in DrawTab
  File "C:\stuff\projektid\skyperious\dist\build\pyinstaller\out00-PYZ.pyz\wx.lib.agw.flatnotebook", line 2033, in DrawTabX
  File "C:\stuff\projektid\skyperious\dist\build\pyinstaller\out00-PYZ.pyz\wx._gdi", line 1294, in __init__
wx._core.PyAssertionError: C++ assertion "bitmap.IsOk()" failed at ..\..\src\msw\bitmap.cpp(1589) in wxMask::Create(): invalid bitmap in wxMask::Create
Traceback (most recent call last):
  File "C:\stuff\projektid\skyperious\dist\build\pyinstaller\out00-PYZ.pyz\wx.lib.agw.shapedbutton", line 714, in OnPaint
  File "C:\stuff\projektid\skyperious\dist\build\pyinstaller\out00-PYZ.pyz\wx.lib.agw.shapedbutton", line 601, in DrawMainButton
  File "C:\stuff\projektid\skyperious\dist\build\pyinstaller\out00-PYZ.pyz\wx._gdi", line 3795, in DrawBitmap
wx._core.PyAssertionError: C++ assertion "bmp.IsOk()" failed at ..\..\src\msw\dc.cpp(1313) in wxMSWDCImpl::DoDrawBitmap(): invalid bitmap in wxMSWDCImpl::DrawBitmap
Traceback (most recent call last):
  File "C:\stuff\projektid\skyperious\dist\build\pyinstaller\out00-PYZ.pyz\wx.lib.agw.ultimatelistctrl", line 7128, in OnPaint
  File "C:\stuff\projektid\skyperious\dist\build\pyinstaller\out00-PYZ.pyz\wx.lib.agw.ultimatelistctrl", line 4547, in DrawInReportMode
  File "C:\stuff\projektid\skyperious\dist\build\pyinstaller\out00-PYZ.pyz\wx.lib.agw.ultimatelistctrl", line 8345, in GetCheckboxImageSize
  File "C:\stuff\projektid\skyperious\dist\build\pyinstaller\out00-PYZ.pyz\wx._gdi", line 6933, in GetBitmap
wx._core.PyAssertionError: C++ assertion "image.IsOk()" failed at ..\..\src\msw\bitmap.cpp(922) in wxBitmap::CreateFromImage(): invalid image
```

Edit: Eventually it will start throwing 'MemoryError' if i keep trying to do things after clicking ignore.

Note: This same chat can be loaded fully in skype itself without issue.

**Comment by suurjaak** [comment]
The thing is that Skyperious cannot display very big chats wholesale, period. Given a sufficiently large chat, at one point the memory will run out.

Technically, it would be possible to create a solution where only those messages are loaded that are currently scrolled into view in the messagelist. A sort of a virtual list, which I assume is what Skype is using. But that would be quite a laborious undertaking, one for which I'm afraid I do not have time. And even that runs into problems - when generating the word cloud, for example. 

So I'm not sure what would be a good solution here. Maybe just a warning that loading failed and to try selecting a shorter period?

What happens if you click Retry or Abort?

If those tracebacks are from the log window, can you show a more complete log?

**Comment by claws61821** [comment]
Does Skyperious have a hard-coded memory limit regardless of architecture, or is this a python or SQL issue at its root?

**Comment by suurjaak** [comment]
There are no hard-coded limits, this is mostly an issue both with how Skyperious was written, and with the Python components it uses.

Firstly, Skyperious is not exactly optimized for low memory usage. If a user looks at a chat history, all the messages currently shown are cached in memory. Not just the message body, but all the message data fields, of which there are a good amount.
And the data structures it uses (Python dicts) bring a sizable overhead if the messages start to number in the thousands.

Secondly, Skyperious is a 32-bit program, meaning it can allocate up to 2GB of memory.
(The "64-bit executable" release is not actually 64-bit, just compiled on a 64-bit architecture. The reason for this is the "Import contacts" functionality, which needs API access to Skype. Since Skype is a 32-bit program, any program accessing its API must also be 32-bit).

Thirdly, the visual components Skyperious uses have their own, completely unknown limitations.

**Comment by rikai** [comment]
The irony is, i don't actually care about viewing the chat history in the program itself, i just want to be able to export the entire log to an html file and have proper statistics on it.

Is it possible to do something like that without having to load the entire log into the program in one go? Segmented exporting and stat tracking that is assembled as a final export at the end?

**Comment by suurjaak** [comment]
Full export is possible and already available in a number of ways:

- selecting the chat in chat lists and clicking "Export chats" -> Export selected into individual files
- loading the chat, choosing the full date range in the filter panel and clicking "Export filter"
- on the program start page, selecting the database and clicking "Export messages" -> Export into separate files

**Comment by claws61821** [comment]
I believe what Rikai is asking for here is a way to automatically split larger chats into smaller segments (ex. 1000 messages, etc) and load and export those sequentially to avoid crashing the program, addending each segment to the same export file when finished. Are you aware of a way to do this in the current builds, and would you be willing to write something similar into the standard export code?

**Comment by suurjaak** [comment]
Closing the issue, as Skyperious has become obsolete, Skype chat history is no longer available to third-party programs.
