### ISSUE TITLE
Trying to merge 2 database cause crash.

### ISSUE THREAD

**Issue by 1337-537h** [suurjaak/Skyperious#43]
Skyperious 3.5
Windows 10 x64 
(skype 6.21)

When trying to merge 2 db always crash (same skype id).
http://i.imgur.com/iwOlD8w.png

**Comment by suurjaak** [comment]
Does it crash for any merge you try to do, or just these two files?

What happens if you try the merge the other way, from the small file to the large file?

Can you open the log window (Help -> Show log window) during merge and see what are the last lines logged when the crash occurs?

**Comment by 1337-537h** [comment]
The other way works fine. Is just 2 conversations of 3 lines only.
I want to keep the chat logs only nothing else, but i want to refresh the freeze pictures of my contacts with a new db but i dont know if is that possible.
http://i.imgur.com/eoGTsbU.png

**Comment by suurjaak** [comment]
One more question - can you enable SQL logging (File -> Advanced options -> LogSQL) and then see what are the last lines in the log window when it crashes?

**Comment by 1337-537h** [comment]
Sure.
There you are http://i.imgur.com/NVyPkl7.png

**Comment by 1337-537h** [comment]
Did you find any solution for the crash?
I also have a second problem.. When trying to see messages 3months plus that appears
http://i.imgur.com/IxVVAfh.jpg

**Comment by suurjaak** [comment]
Closing the issue, as the program has become obsolete.

**Comment by suurjaak** [comment]
FYI: I have brought Skyperious out of obsolescence with the latest version 4.0. Is this issue still relevant?

**Comment by 1337-537h** [comment]
lol i dont know i dont try it but the new skype is so lame the logs are online not like the all version and i dont know if i keep trying to keep my chatlogs :(

**Comment by suurjaak** [comment]
Well, with the latest Skyperious version, you actually can keep all your chatlogs, simply by having Skyperious sync the messages now and then. You can even automate this, using the command-line interface.

**Comment by 1337-537h** [comment]
Error syncing from Skype online service:

Traceback (most recent call last):
  File "workers.py", line 849, in run
  File "live.py", line 549, in populate
  File "live.py", line 601, in populate_history
  File "live.py", line 182, in save
  File "live.py", line 477, in convert
  File "urllib.py", line 1306, in quote
KeyError: u'\u0392'

**Comment by suurjaak** [comment]
Thank you for reporting this. I have released a bugfix, v4.0.1.

**Comment by 1337-537h** [comment]
Error syncing from Skype online service:

Traceback (most recent call last):
  File "workers.py", line 849, in run
  File "live.py", line 569, in populate
  File "live.py", line 629, in populate_history
  File "logging\__init__.py", line 1207, in exception
  File "logging\__init__.py", line 1200, in error
  File "logging\__init__.py", line 1293, in _log
  File "logging\__init__.py", line 1303, in handle
  File "logging\__init__.py", line 1343, in callHandlers
  File "logging\__init__.py", line 766, in handle
  File "guibase.py", line 77, in emit
  File "lib\util.py", line 436, in to_unicode
  File "site-packages\skpy\core.py", line 90, in __str__
UnicodeEncodeError: 'ascii' codec can't encode characters in position 271-273: ordinal not in range(128)

**Comment by suurjaak** [comment]
@1337-537h: Should be fixed in the newest version, 4.1.
