### ISSUE TITLE
CLI is unavailable when wxPython is not installed

### ISSUE THREAD

**Issue by kirov** [suurjaak/Skyperious#45]
Skyperious 3.5
OS X 10.11

So I've upgraded to 3.5, and I wasn't able to run it until I installed wxPython (which I don't need at all).

    (skyperious)skyperious$ ./skyperious.sh  --help
    readlink: illegal option -- f
    usage: readlink [-n] [file ...]
    Traceback (most recent call last):
      File "./skyperious/main.py", line 47, in <module>
        import export
      File "/Applications/skyperious/skyperious/export.py", line 33, in <module>
        import main
      File "/Applications/skyperious/skyperious/main.py", line 48, in <module>
        import skypedata
      File "/Applications/skyperious/skyperious/skypedata.py", line 46, in <module>
        import support
      File "/Applications/skyperious/skyperious/support.py", line 27, in <module>
        import wx
    ImportError: No module named wx

However the readme says:
> If wxPython is not available, the command line interface will function regardless. If other Python libraries are not available, the program will function regardless, only with lesser service - like lacking Excel export or full search syntax.

**Comment by suurjaak** [comment]
Oops, indeed wxPython should not be required. Thank you for reporting this.

Fixed in GitHub master, can you verify that it works properly now? I will update the pip repository later.

**Comment by kirov** [comment]
It works now, thanks.
