### ISSUE TITLE
I installed Skyperious using pip on Mac OSx 10.11.1

### ISSUE THREAD

**Issue by MohamedDiaa** [suurjaak/Skyperious#46]
I installed Skyperious using pip on Mac OSx 10.11.1
then I tried to start  Skyperious on shell this is the shell output

Traceback (most recent call last):
  File "/usr/local/bin/skyperious", line 7, in <module>
    from skyperious.main import run
  File "/Library/Python/2.7/site-packages/skyperious/main.py", line 47, in <module>
    import export
  File "/Library/Python/2.7/site-packages/skyperious/export.py", line 34, in <module>
    import skypedata
  File "/Library/Python/2.7/site-packages/skyperious/skypedata.py", line 46, in <module>
    import support
  File "/Library/Python/2.7/site-packages/skyperious/support.py", line 27, in <module>
    import wx
ImportError: No module named wx

**Comment by suurjaak** [comment]
This is related to #45. The fix is available in the GitHub repository, but not yet in pip.

Until the next program version gets released, a quick fix could be replacing your `/Library/Python/2.7/site-packages/skyperious/support.py` with https://raw.githubusercontent.com/suurjaak/Skyperious/master/skyperious/support.py.

**Comment by asmaier** [comment]
Another workaround is to install wxPython with homebrew:

    $ brew install wxpython
    $ pip install skyperious
    $ skyperious -h
    usage: skyperious [-h] [--verbose] {export,search,merge,diff,gui} ...
    ...
