### ISSUE TITLE
Can't export my chats

### ISSUE THREAD

**Issue by bodqhrohro** [suurjaak/Skyperious#61]
```
Error exporting chats: 'ascii' codec can't decode byte 0xd0 in position 58: ordinal not in range(128)

Traceback (most recent call last):
  File "/home/bodqhrohro/.local/lib/python2.7/site-packages/skyperious/main.py", line 396, in run_export
    format[:4].upper(), dbstr, target))
  File "/home/bodqhrohro/.local/lib/python2.7/site-packages/skyperious/main.py", line 751, in output
    print(*args, **kwargs)
  File "/usr/lib/python2.7/codecs.py", line 369, in write
    data, consumed = self.encode(object, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 58: ordinal not in range(128)
```

**Comment by suurjaak** [comment]
Should be fixed in the latest version, 3.6.
