### ISSUE TITLE
Python can`t fine module ConfigParser

### ISSUE THREAD

**Issue by arun-gurung** [suurjaak/Skyperious#82]
#python -m skyperious
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/root/src/Skyperious-4.2/skyperious/__init__.py", line 1, in <module>
    from . import conf
  File "/root/src/Skyperious-4.2/skyperious/conf.py", line 16, in <module>
    from ConfigParser import RawConfigParser
ModuleNotFoundError: No module named 'ConfigParser'

**Comment by suurjaak** [comment]
Skyperious uses Python2, Python 3 is not supported.

**Comment by arun-gurung** [comment]
I got it working with Python2 now.
