### ISSUE TITLE
Unable to export with command line

### ISSUE THREAD

**Issue by tspivey** [suurjaak/Skyperious#86]
On both 4.3 and latest git master, skyperious export no longer works.
python -m skyperious export main.db gives me:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/tyler/Skyperious/skyperious/__main__.py", line 5, in <module>
    main.run()
  File "skyperious/main.py", line 801, in run
    run_export(arguments.FILE, arguments.type, arguments.output,
AttributeError: 'Namespace' object has no attribute 'output'
```

**Comment by suurjaak** [comment]
Confirmed. 

Fixed in latest release, v4.3.1. 

Thank you for reporting this.
