### ISSUE TITLE
Attribute Error: 'dict' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by 29988122** [suurjaak/Skyperious#92]
I'm using windows binary 64bit on Windows 10.

![圖片](https://user-images.githubusercontent.com/5474709/104336296-3a028680-552f-11eb-85d2-5e3080662109.png)

I imported the chat jsons from https://support.skype.com/en/faq/FA34894/how-do-i-export-my-skype-files-and-chat-history
as some of the group chats can't be retreived by Skyperious. They're parsed correctly(probably), judging from the total parsed chat numbers.

What should I do? Clean up my python enviroment or using linux VM instead?
Also, I can't find stack trace or log files under C:\Users\AppData\Local\Skyperious.

**Comment by suurjaak** [comment]
There is a more detailed log available under menu Help -> Show log window. 

If you try importing again, you should see a full stack trace there. Can you paste the result here?

**Comment by 29988122** [comment]
Thanks for the timely response!
```
2021-01-12 22:42:44.202	Started application.
2021-01-12 22:42:59.522	Creating new database C:\Users\Jerry Ho\Desktop\a29988122.main.db from Skype export C:\Users\Jerry Ho\Desktop\messages.json, user 'a29988122'.
2021-01-12 22:42:59.528	Parsing Skype export file C:\Users\Jerry Ho\Desktop\messages.json.
2021-01-12 22:42:59.567	Inserting 1 row into table Accounts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 22:42:59.572	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 22:42:59.584	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 22:42:59.595	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 22:42:59.604	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 22:42:59.615	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 22:42:59.636	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 22:42:59.697	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 22:42:59.718	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 22:43:00.713	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 22:43:00.749	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 22:43:01.042	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 22:43:01.049	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 22:43:01.057	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 22:43:01.064	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 22:43:01.068	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 22:43:01.077	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 22:43:01.094	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 22:43:01.101	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 22:43:01.110	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 22:43:01.118	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 22:43:01.126	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 22:43:01.134	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 22:43:01.141	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 22:43:01.148	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 22:43:01.156	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 22:43:01.163	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 22:43:01.176	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 22:43:01.187	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 22:43:01.191	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 22:43:01.198	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 22:43:01.205	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 22:43:01.212	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 22:43:01.219	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 22:43:01.230	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 22:43:01.237	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 22:43:01.247	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 22:43:01.254	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 22:43:01.261	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 22:43:01.271	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 22:43:01.279	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 22:54:50.413	Error parsing file from {'convo_id': 11, 'author': u'a29988122', 'pk_id': 1556467273824L, 'timestamp': 1556467273, 'body_xml': u'', '__type': u'RichText/Media_GenericFile', '__generated': True, 'type': 68, 'chatmsg_type': 7, 'guid': '`\xd0\xaddj\x01\x00\x00`\xd0\xaddj\x01\x00\x00`\xd0\xaddj\x01\x00\x00`\xd0\xaddj\x01\x00\x00', 'is_permanent': 1, 'timestamp__ms': 1556467273824.0}.

			Traceback (most recent call last):
			  File "live.py", line 1072, in export_finalize_message
			AttributeError: 'NoneType' object has no attribute 'get'

2021-01-12 22:54:50.414	Error parsing file from {'edited_timestamp': 1556467273L, 'convo_id': 11, 'edited_by': u'a29988122', 'author': u'a29988122', 'pk_id': 1556467263604L, 'timestamp': 1556467262, 'body_xml': '', '__type': u'RichText/Media_GenericFile', 'type': 68, 'chatmsg_type': 7, 'guid': 't\xa8\xaddj\x01\x00\x00t\xa8\xaddj\x01\x00\x00t\xa8\xaddj\x01\x00\x00t\xa8\xaddj\x01\x00\x00', 'is_permanent': 1, 'timestamp__ms': 1556467262966.0}.

			Traceback (most recent call last):
			  File "live.py", line 1072, in export_finalize_message
			AttributeError: 'NoneType' object has no attribute 'get'

2021-01-12 22:57:01.177	Error parsing file from {'convo_id': 11, 'type': 68, 'author': u'jokermoon56', 'pk_id': 1545611366749L, 'timestamp': 1545611366, 'body_xml': u'', '__type': u'RichText/Media_GenericFile', '__generated': True, 'from_dispname': u'\u5468\u76ca\u8aa0(Joker)', 'chatmsg_type': 7, 'guid': ']\xd1\x9d\xddg\x01\x00\x00]\xd1\x9d\xddg\x01\x00\x00]\xd1\x9d\xddg\x01\x00\x00]\xd1\x9d\xddg\x01\x00\x00', 'is_permanent': 1, 'timestamp__ms': 1545611366749.0}.

			Traceback (most recent call last):
			  File "live.py", line 1072, in export_finalize_message
			AttributeError: 'NoneType' object has no attribute 'get'

2021-01-12 22:57:01.178	Error parsing file from {'edited_timestamp': 1545611366L, 'convo_id': 11, 'edited_by': u'jokermoon56', 'author': u'jokermoon56', 'pk_id': 1545611359482L, 'timestamp': 1545611356, 'body_xml': '', 'type': 68, '__type': u'RichText/Media_GenericFile', 'from_dispname': u'\u5468\u76ca\u8aa0(Joker)', 'chatmsg_type': 7, 'guid': '\xfa\xb4\x9d\xddg\x01\x00\x00\xfa\xb4\x9d\xddg\x01\x00\x00\xfa\xb4\x9d\xddg\x01\x00\x00\xfa\xb4\x9d\xddg\x01\x00\x00', 'is_permanent': 1, 'timestamp__ms': 1545611356516.0}.

			Traceback (most recent call last):
			  File "live.py", line 1072, in export_finalize_message
			AttributeError: 'NoneType' object has no attribute 'get'

2021-01-12 23:00:53.600	Error parsing file from {'convo_id': 11, 'type': 68, 'author': u'ddknightg', 'pk_id': 1525096600127L, 'timestamp': 1525096600, 'body_xml': u'Edited previous message: <e_m ts="1525096597" ts_ms="1525096597000" a="ddknightg" t="254"/>', '__type': u'RichText/Media_GenericFile', 'from_dispname': u'ddknight', 'chatmsg_type': 7, 'guid': '?R\xd7\x16c\x01\x00\x00?R\xd7\x16c\x01\x00\x00?R\xd7\x16c\x01\x00\x00?R\xd7\x16c\x01\x00\x00', 'is_permanent': 1, 'timestamp__ms': 1525096600120.0}.

			Traceback (most recent call last):
			  File "live.py", line 1072, in export_finalize_message
			AttributeError: 'NoneType' object has no attribute 'get'

2021-01-12 23:03:14.480	Error parsing file from {'convo_id': 11, 'author': u'a29988122', 'pk_id': 1507964126031L, 'timestamp': 1507964126, 'body_xml': u'Edited previous message: <e_m ts="1507964123" ts_ms="1507964123000" a="a29988122" t="254"/>', '__type': u'RichText/Media_GenericFile', 'type': 68, 'chatmsg_type': 7, 'guid': 'O\x83\xaa\x19_\x01\x00\x00O\x83\xaa\x19_\x01\x00\x00O\x83\xaa\x19_\x01\x00\x00O\x83\xaa\x19_\x01\x00\x00', 'is_permanent': 1, 'timestamp__ms': 1507964126024.0}.

			Traceback (most recent call last):
			  File "live.py", line 1072, in export_finalize_message
			AttributeError: 'NoneType' object has no attribute 'get'

2021-01-12 23:07:40.666	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:07:40.691	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:07:40.707	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:07:40.724	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:07:40.740	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:07:40.757	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:07:40.774	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:07:40.791	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:07:40.814	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:14:44.218	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:20:42.582	Error parsing file from {'convo_id': 12, 'author': u'a29988122', 'pk_id': 1521030764113L, 'timestamp': 1521030764, 'body_xml': u'Edited previous message: <e_m ts="1521030762" ts_ms="1521030762000" a="a29988122" t="254"/>', '__type': u'RichText/Media_GenericFile', 'type': 68, 'chatmsg_type': 7, 'guid': 'Q\x96\x7f$b\x01\x00\x00Q\x96\x7f$b\x01\x00\x00Q\x96\x7f$b\x01\x00\x00Q\x96\x7f$b\x01\x00\x00', 'is_permanent': 1, 'timestamp__ms': 1521030764108.0}.

			Traceback (most recent call last):
			  File "live.py", line 1072, in export_finalize_message
			AttributeError: 'NoneType' object has no attribute 'get'

2021-01-12 23:24:48.445	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:26:51.914	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:28:00.285	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:28:20.755	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:28:20.930	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:29:08.360	Error parsing file from {'convo_id': 15, 'type': 68, 'author': u'nicedate2', 'pk_id': 1522257098937L, 'timestamp': 1522257098, 'body_xml': u'', '__type': u'RichText/Media_GenericFile', 'dialog_partner': u'nicedate2', 'from_dispname': u'JAG/justagame/nicedate', 'chatmsg_type': 7, 'guid': '\xb9\xf8\x97mb\x01\x00\x00\xb9\xf8\x97mb\x01\x00\x00\xb9\xf8\x97mb\x01\x00\x00\xb9\xf8\x97mb\x01\x00\x00', 'is_permanent': 1, 'timestamp__ms': 1522257098255.0}.

			Traceback (most recent call last):
			  File "live.py", line 1072, in export_finalize_message
			AttributeError: 'NoneType' object has no attribute 'get'

2021-01-12 23:30:42.630	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:30:42.901	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:31:07.484	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:31:07.542	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:31:07.611	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:31:07.663	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:31:07.688	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:31:07.715	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:31:07.941	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:31:07.969	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:31:08.103	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:31:08.175	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:31:10.819	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:31:11.470	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:31:11.598	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:31:11.625	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:31:11.758	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:31:11.893	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:31:11.910	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:31:11.944	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:31:11.952	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:31:12.219	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:31:12.369	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:31:12.428	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:31:12.477	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:31:12.527	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:31:12.552	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:31:12.577	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:31:12.593	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:31:12.620	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:31:12.749	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:31:12.800	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:31:12.827	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:31:12.851	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:31:15.844	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:32:46.076	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:32:46.105	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:32:46.159	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:32:47.110	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:32:53.745	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:32:53.892	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:32:58.497	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:32:58.533	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:32:58.949	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:32:59.301	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:32:59.311	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:32:59.909	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:33:00.169	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:33:00.205	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:33:00.248	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:33:00.265	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:02.908	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:10.158	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:10.218	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:10.325	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:10.376	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:12.300	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:12.440	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:12.577	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:12.719	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:12.761	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:12.804	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:12.830	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:12.876	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:12.943	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:12.988	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:13.136	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:13.271	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:13.305	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:13.433	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:13.467	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:13.625	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:13.779	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:13.938	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:14.070	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:14.111	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:14.271	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:14.433	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:14.654	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:14.974	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:15.292	Inserting 1 row into table Contacts, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:15.377	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:15.755	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:16.111	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:16.464	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:16.833	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:17.221	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:17.573	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:17.944	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:18.157	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:18.715	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:19.131	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:19.427	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:19.748	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:19.948	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:20.109	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:20.280	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:20.342	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:20.411	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:20.472	Inserting 1 row into table Conversations, C:\Users\Jerry Ho\Desktop\a29988122.main.db.
2021-01-12 23:34:20.564	Error parsing Skype export C:\Users\Jerry Ho\Desktop\messages.json.

			Traceback (most recent call last):
			  File "workers.py", line 864, in run
			  File "live.py", line 873, in export_read
			  File "live.py", line 966, in export_parse
			  File "live.py", line 1264, in id_to_identity
			AttributeError: 'dict' object has no attribute 'endswith'

```
I also tried the dockerfile, but I guess that's out of date, so error is kinda normal.
![圖片](https://user-images.githubusercontent.com/5474709/104343393-da0fde00-5536-11eb-9507-0fdcc8c99b69.png)

BTW, If you really need the messeage.json file to debug, please give me a mail address so I can send the link to you(165mb text, json only) - I literally have 0 idea how many sensitive personal infos are there...xD

**Comment by suurjaak** [comment]
Interesting, apparently your export file has a somewhat different structure. 

Having the messages.json file would certainly help in tracking down the difference, but I'm somewhat loathe to delve into your personal communications. However, if you are okay with it, you can send the file to my e-mail, erki@lap.ee (zipped, please). Or if you have DropBox or the like, you can upload the file there and send me the link. 

Alternatively, can you open the file in a text editor or the like, and search for all occurrences of `"members":`? Typically, they ought to be something along the lines of

    "members":"[\"8:username1\",\"8:username2\"]"

But it seems there is at least one where the contents have more structure and contain dicts instead.

**Comment by 29988122** [comment]
> Edited to add: I edited the log you pasted to remove personal information.

Mail sent. : D

Regarding the dict structure, I'm not so sure about what kind of datatype that is... both prettify json/beautify of VScode refused to clean this huge json file.

If this info is of any help, there's mainly two group chats that cannot be retrieved via Skyperious's login function, named ```2021 maga``` and ```No king rules forever my son``` respectively. (I don't live in the US, so the group name is a joke for obvious reasons.)
That's why I seek for the data export function provided my microsoft, and import json to Skyperious later on.

**Comment by suurjaak** [comment]
Ta, I got the file, so you can remove it from online now.

And I found the problem. Indeed, a few chat entries have the memberlist in a completely different form. I'll update the program so at least it can handle such entries, and in general won't error out on unexpected data on import. 

Do you know what kind of chats those might be? They seem to have something to do with casting (screencasting?), and their display names all start with "Call parent thread". The last such had traffic on August 2nd, 2017.

**Comment by 29988122** [comment]
TBH, I have 0 idea after checking those entries.

This skype account has experienced a few changes:
-MSN messenger shutdown, migrated to skype(2013)
-merge msn account %user%@messengeruser.com with skype account
-associate skype account with microsoft account

I'd assume the weird Call parent thread data structure happened in between the events.

I'm glad the edge condition's been found relatively speedy without too much hassle.
Thank you suurjaak for keep maintaining this repo! You rock. 
: D

**Comment by suurjaak** [comment]
Fixed the error in live sync. 

Also fixed the issue with Dockerfile. 

Can you confirm that live sync works for you now?

**Comment by 29988122** [comment]
Yes, I can confirm that
-the import function works 
-the login and sync works
![圖片](https://user-images.githubusercontent.com/5474709/105102597-f9d07480-5ae9-11eb-9080-367fd9acffbf.png)

Thanks again, suurjakk. This is so useful to me! 
: D
